### ISSUE TITLE
error with read_float_genarray

### ISSUE THREAD

**Issue by mars0i** [vbrankov/hdf5-ocaml#13]
The following example uses [Owl](https://github.com/ryanrhymes/owl) to create a `Bigarray` genarray (that's what Owl matrices are), write it to a file, and then read it back in.  The example works perfectly in hdf5-ocaml v. 0.1.3, but not in the current version of `hdf5-ocaml` (with the addition of PR #11).
```ocaml
open Hdf5_caml

let () =
  let m = Owl.Mat.uniform 10 10 in
  let f = H5.create_trunc "foo.h5" in
  H5.write_float_genarray f "m" m;
  H5.close f;

  let f = H5.open_rdonly "foo.h5" in
  let m' = H5.read_float_genarray f "m" Bigarray.c_layout in
  H5.close f;
  Printf.printf "original data = data from file: %b\n" (m = m')
```
With the current version, this line
```
  let m' = H5.read_float_genarray f "m" Bigarray.c_layout in
```
causes these error messages, and the rest of the code isn't executed:
```
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5Dio.c line 269 in H5Dwrite(): can't prepare for writing data
    major: Dataset
    minor: Write failed
  #001: H5Dio.c line 345 in H5D__pre_write(): can't write data
    major: Dataset
    minor: Write failed
  #002: H5Dio.c line 638 in H5D__write(): no write intent on file
    major: Dataset
    minor: Write failed
Fatal error: exception Hdf5_raw.H5i.Fail
```
It's strange that the error messages are about writes, since it seems to be a read that causes the eeror.  However, commenting out the `read_float_genarray` line gets rid of the errors, and afaics every other line seems to execute without problem.

There is no similar problem with `write_float_array` and `read_float_array`, btw.  I have only seen the problem with `read_float_genarray`.

(I did some searching for similar errors on the web.  There are quite a few cases in which these HDF5 errors have come up, but none of them seemed similar to this case.  For example, some of the instances of these errors had to do with writing files of certain large sizes.)

**Comment by vbrankov** [comment]
This should be fixed now.

**Comment by mars0i** [comment]
Great--thanks.
