### ISSUE TITLE
required hdf version?

### ISSUE THREAD

**Issue by nilsbecker** [vbrankov/hdf5-ocaml#2]
i have problems loading hdf5-ocaml from utop. i have hdf5.10 installed. i get

```
#require "hdf5_caml";;
Error: The external function `hdf5_h5tb_write_records_bytecords' is not available
```

this is after a reinstall of hdf5-ocaml via opam. before i got the message 

```
cannot load required shared library dllhdf5_raw_stubs.
  Reason: /Users/<USER>/.opam/4.02.3/lib/stublibs/dllhdf5_raw_stubs.so:
dlopen(/Users/<USER>/.opam/4.02.3/lib/stublibs/dllhdf5_raw_stubs.so, 138):
Library not loaded: /usr/local/lib/libhdf5.9.dylib Referenced from:
/Users/<USER>/.opam/4.02.3/lib/stublibs/dllhdf5_raw_stubs.so
  Reason: image not found.
Error: The external function `hdf5_h5l_exists' is not available
```

**Comment by nilsbecker** [comment]
actually, i can successfully load hdf5_raw and run the first example for it on the website. just the high-level interface cannot be loaded

**Comment by nilsbecker** [comment]
i reinstalled from git master. the problem persists. this is on os x (yosemite first, now el capitan).

**Comment by vbrankov** [comment]
Looks like hdf5_hl library is missing.  What is the output of "locate libhdf5_hl.so" or "locate libhdf5_serial_hl.so"?  What is your version of Linux?

**Comment by nilsbecker** [comment]
as i worte, it's os x. i don't have locate installed. i did `find . -name *libhdf5*` inside `.opam` and nothing came up. are these files part of the bindings or are they part of hdf5 itself?

**Comment by vbrankov** [comment]
These files are a part of HDF5 and not of the bindings.  If you check out the section [depexts](https://github.com/vbrankov/hdf5-ocaml/blob/master/opam), OPAM requires package dependencies for each OS.  Do you have HDF5 working in Python?

**Comment by nilsbecker** [comment]
yes, it is working in python. i am using the anaconda python distribution. but i also have hdf5 1.8.16_1 installed via homebrew. (ie. in /usr/local). 

in ipython, the hdf5 version string given by h5py is 1.18.15 which makes me think that it's actually using a copy of hdf5 shipped with anaconda.

**Comment by vbrankov** [comment]
What does "ldd hdf5_executable" output?

**Comment by nilsbecker** [comment]
`-bash: ldd: command not found` what is the os x equivalent? (sorry for being noobish, i am not familiar with compiling C programs on mac). i do have the xcode command line tools installed though.

**Comment by vbrankov** [comment]
Sorry, I just read a little about utop.  I'm using vim so I'm not entirely familiar how plugins are added to Emacs.

Speaking about ldd, this thread says that the OS X equivalent is "otool -L": https://discussions.apple.com/thread/309193?start=0&tstart=0

**Comment by nilsbecker** [comment]
" I'm using vim so I'm not entirely familiar how plugins are added to Emacs." 

not sure what you mean here, i'm using vim as well, but for interactive repl i use utop. nothing to do with emacs. (?)

anyway, the library is installed by homebrew in `/usr/local/opt/hdf5` and then `lib, include` and so on. if i do `otool -L libhdf5.dylib` in the `lib` subdirectory, i get for example:

```
libhdf5.dylib:
    /usr/local/opt/hdf5/lib/libhdf5.10.dylib (compatibility version 12.0.0, current version 12.0.0)
    /usr/local/opt/szip/lib/libsz.2.dylib (compatibility version 3.0.0, current version 3.0.0)
    /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

**Comment by vbrankov** [comment]
I found it.  There's a bug in the HDF5 library that prevents it from working in utop.  I'll fix it and republish it in OPAM.  It may take a few days to get through OPAM.

**Comment by nilsbecker** [comment]
cool. so you say if i use the regular toplevel it should work already now?

**Comment by nilsbecker** [comment]
i tried in the regular toplevel `ocaml`. also here, the library does not load for me.

```
#use "topfind";;
#require "hdf5_raw";;
/Users/nbecker/.opam/4.02.3/lib/hdf5_raw: added to search path
/Users/nbecker/.opam/4.02.3/lib/hdf5_raw/hdf5_raw.cma: loaded
Cannot load required shared library dllhdf5_raw_stubs.
Reason: /Users/nbecker/.opam/4.02.3/lib/stublibs/dllhdf5_raw_stubs.so: dlopen(/Users/nbecker/.opam/4.02.3/lib/stublibs/dllhdf5_raw_stubs.so, 138): Symbol not found: _caml_ba_alloc_dims
  Referenced from: /Users/nbecker/.opam/4.02.3/lib/stublibs/dllhdf5_raw_stubs.so
  Expected in: flat namespace
 in /Users/nbecker/.opam/4.02.3/lib/stublibs/dllhdf5_raw_stubs.so.
```

so here there is a problem already with `_raw` where utop does not complain. the same error occurs with `_caml` as well.

**Comment by vbrankov** [comment]
I don't think any bytecode will work.  Only the native compilation works.

**Comment by nilsbecker** [comment]
i see.

**Comment by nilsbecker** [comment]
hi, is this issue supposed to be resolved in the current opam version of hdf5? for me it still does not work unfortunately. the current situation is:

`otool -L libhdf5.dylib` from `~` -> can't open file
the same from `/usr/local/opt/hdf5/lib/` -> it finds bunch of .dylib files

in the ocaml toplevel, i still get the same error as on january 11 when trying to load `hdf5_raw`

**Comment by nilsbecker** [comment]
i tried to compile a native code program. i copied the first example from the readme file to a file `hdf5test.ml` and called `ocamlbuild -pkg hdf5 hdf5test.native` which complained that the package hdf5 was not found. is this supposed to work? i also tried with `-pkg hdf5_caml` which complains about unbound module H5 -- at least it seems `hdf5_caml` is found...

**Comment by vbrankov** [comment]
I'm sorry, I didn't get around to publish the fix to the OPAM.  I'll get to it right away.

**Comment by nilsbecker** [comment]
ok, thanks. however, i also tried to clone the repo to a local directory and opam -pinned it. with that version, i was also not able to run the example. so it could be that the fix does not work for me...

**Comment by vbrankov** [comment]
The examples had bugs, fixed now.  They can be built with:

``` shell
ocamlbuild -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native
ocamlbuild -tag "ppx(ppx_h5struct)" -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native
```

I'll submit the (hopefully) fixed version to OPAM.

**Comment by nilsbecker** [comment]
ok, i tried this. git pulled from master, upgraded the pinned hdf5 via opam. i then saved the new first example from the README as hdf5test.native (the line defining the module H5 is different). then i ran
`ocamlbuild -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native`. 

i get the error:

```
ocamlbuild -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native
+ ocamlfind ocamlopt -linkpkg -package hdf5_caml -package hdf5_raw -package bigarray hdf5test.cmx -o hdf5test.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Bigarray referenced from /Users/nbecker/.opam/4.02.3/lib/hdf5_raw/hdf5_raw.cmxa(Hdf5_raw),
           /Users/nbecker/.opam/4.02.3/lib/hdf5_caml/hdf5_caml.cmxa(Hdf5_caml)
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled ... [etc etc]
```

**Comment by vbrankov** [comment]
What is produced by this command?

``` shell
ocamlfind query bigarray
```

**Comment by nilsbecker** [comment]
this: `/Users/nbecker/.opam/4.02.3/lib/ocaml`. i've used bigarray before, never seemed to be a problem. 

just for clarity: this is the example .ml i tried:

```
module H5 = Hdf5_caml.H5caml

let () =
  let a = [| 0.; 1.; 2. |] in

  let output = H5.create_trunc "file.h5" in
  H5.write_float_array output "a" a;
  H5.close output;

  let input = H5.open_rdonly "file.h5" in
  let b = H5.read_float_array input "a" in
  H5.close input;

  assert (a = b)
```

**Comment by nilsbecker** [comment]
this file:

```
open Bigarray

let a = Array1.of_array Float64 C_layout [|0.|]
```

compiles fine with 

```
ocamlbuild -pkg bigarray bigarraytest.native
```

**Comment by vbrankov** [comment]
Can you please put "open Bigarray" on the top of the HDF5 example?

**Comment by nilsbecker** [comment]
ok, will try. i now have

```
open Bigarray
module H5 = Hdf5_caml.H5caml

let () =
  let a = [| 0.; 1.; 2. |] in

  let output = H5.create_trunc "file.h5" in
  H5.write_float_array output "a" a;
  H5.close output;

  let input = H5.open_rdonly "file.h5" in
  let b = H5.read_float_array input "a" in
  H5.close input;

  assert (a = b)
```

i still get the same error when compiling with

```
ocamlbuild -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native
```

(actually, Bigarray was not really used directly in the script anyway, so i would not expect opening it to make a difference?)

**Comment by vbrankov** [comment]
Can you please delete the folder _build and rebuild using:

``` shell
ocamlbuild -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native -verbose 0
```

**Comment by nilsbecker** [comment]
ok, sure. this is the session:

```
bqdyn253_067:tmp nbecker$ ocamlbuild -clean
Finished, 0 targets (0 cached) in 00:00:00.
bqdyn253_067:tmp nbecker$ ls _build
ls: _build: No such file or directory
bqdyn253_067:tmp nbecker$ ocamlbuild -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native -verbose 0
ocamlfind ocamldep -package hdf5_caml -package hdf5_raw -package bigarray -modules hdf5test.ml > hdf5test.ml.depends
ocamlfind ocamlc -c -package hdf5_caml -package hdf5_raw -package bigarray -o hdf5test.cmo hdf5test.ml
ocamlfind ocamlopt -c -package hdf5_caml -package hdf5_raw -package bigarray -o hdf5test.cmx hdf5test.ml
ocamlfind ocamlopt -linkpkg -package hdf5_caml -package hdf5_raw -package bigarray hdf5test.cmx -o hdf5test.native
+ ocamlfind ocamlopt -linkpkg -package hdf5_caml -package hdf5_raw -package bigarray hdf5test.cmx -o hdf5test.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Bigarray referenced from /Users/nbecker/.opam/4.02.3/lib/hdf5_raw/hdf5_raw.cmxa(Hdf5_raw),
           /Users/nbecker/.opam/4.02.3/lib/hdf5_caml/hdf5_caml.cmxa(Hdf5_caml)
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.

  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:

      true: -traverse
      <dir1> or <dir2>: traverse

bqdyn253_067:tmp nbecker$ ocamlbuild -clean
Finished, 0 targets (0 cached) in 00:00:00.
bqdyn253_067:tmp nbecker$ ls _build
ls: _build: No such file or directory
bqdyn253_067:tmp nbecker$ ocamlbuild -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native -verbose 0
ocamlfind ocamldep -package hdf5_caml -package hdf5_raw -package bigarray -modules hdf5test.ml > hdf5test.ml.depends
ocamlfind ocamlc -c -package hdf5_caml -package hdf5_raw -package bigarray -o hdf5test.cmo hdf5test.ml
ocamlfind ocamlopt -c -package hdf5_caml -package hdf5_raw -package bigarray -o hdf5test.cmx hdf5test.ml
ocamlfind ocamlopt -linkpkg -package hdf5_caml -package hdf5_raw -package bigarray hdf5test.cmx -o hdf5test.native
+ ocamlfind ocamlopt -linkpkg -package hdf5_caml -package hdf5_raw -package bigarray hdf5test.cmx -o hdf5test.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Bigarray referenced from /Users/nbecker/.opam/4.02.3/lib/hdf5_raw/hdf5_raw.cmxa(Hdf5_raw),
           /Users/nbecker/.opam/4.02.3/lib/hdf5_caml/hdf5_caml.cmxa(Hdf5_caml)
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.

  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:

      true: -traverse
      <dir1> or <dir2>: traverse
```

**Comment by nilsbecker** [comment]
and then

```
bqdyn253_067:tmp nbecker$ ls _build
_digests            hdf5test.cmi        hdf5test.cmx        hdf5test.ml.depends ocamlc.where
_log                hdf5test.cmo        hdf5test.ml         hdf5test.o
```

**Comment by nilsbecker** [comment]
also `less _build/_log` gives

```
### Starting build.
# Target: hdf5test.ml.depends, tags: { extension:ml, file:hdf5test.ml, ocaml, ocamldep, package(bigarray), package(hdf5_caml), package(hdf5_raw), quiet }
ocamlfind ocamldep -package hdf5_caml -package hdf5_raw -package bigarray -modules hdf5test.ml > hdf5test.ml.depends
# Target: hdf5test.cmo, tags: { byte, compile, extension:cmo, extension:ml, file:hdf5test.cmo, file:hdf5test.ml, implem, ocaml, package(bigarray), package(hdf5_caml), package(hdf5_raw), quiet }
ocamlfind ocamlc -c -package hdf5_caml -package hdf5_raw -package bigarray -o hdf5test.cmo hdf5test.ml
# Target: hdf5test.cmx, tags: { compile, extension:cmx, extension:ml, file:hdf5test.cmx, file:hdf5test.ml, implem, native, ocaml, package(bigarray), package(hdf5_caml), package(hdf5_raw), quiet }
ocamlfind ocamlopt -c -package hdf5_caml -package hdf5_raw -package bigarray -o hdf5test.cmx hdf5test.ml
# Target: hdf5test.native, tags: { dont_link_with, extension:native, file:hdf5test.native, link, native, ocaml, package(bigarray), package(hdf5_caml), package(hdf5_raw), program, quiet }
ocamlfind ocamlopt -linkpkg -package hdf5_caml -package hdf5_raw -package bigarray hdf5test.cmx -o hdf5test.native
+ ocamlfind ocamlopt -linkpkg -package hdf5_caml -package hdf5_raw -package bigarray hdf5test.cmx -o hdf5test.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Bigarray referenced from /Users/nbecker/.opam/4.02.3/lib/hdf5_raw/hdf5_raw.cmxa(Hdf5_raw),
           /Users/nbecker/.opam/4.02.3/lib/hdf5_caml/hdf5_caml.cmxa(Hdf5_caml)
Command exited with code 2.
# Compilation unsuccessful.
```

**Comment by vbrankov** [comment]
What's the version of your ocamlbuild?  Mine is 4.02.3.

**Comment by nilsbecker** [comment]
```
bqdyn253_067:tmp nbecker$ ocamlbuild -version
ocamlbuild 4.02.3
```

**Comment by vbrankov** [comment]
Is it run from the OPAM repo?  `opam show ocamlbuild`

**Comment by nilsbecker** [comment]
```
qdyn253_067:tmp nbecker$ opam show ocamlbuild
             package: ocamlbuild
             version: 0
          repository: default
            homepage: https://github.com/ocaml/ocaml
         bug-reports: http://caml.inria.fr/mantis/
            dev-repo: https://github.com/ocaml/ocaml.git
              author: Nicolas Pouillard, Berke Durak
             license: LGPL-2 with OCaml linking exception
                 doc: http://caml.inria.fr/pub/docs/manual-ocaml/ocamlbuild.html, https://github.com/gasche/manual-ocamlbuild/blob/master/manual.md
             depends: base-ocamlbuild
   installed-version: 0 [4.02.3]
  available-versions: 0, 0.9.0, 0.9.1
         description: Build system distributed with the OCaml compiler since OCaml 3.10.0
```

**Comment by nilsbecker** [comment]
could it be that something with my HDF5 installation is fishy but it shows up somehow when linking Bigarray? ie. that the error message is misleading?

**Comment by vbrankov** [comment]
It could be.  My ocamlbuild's output is different than yours.  It's

``` shell
$ ocamlbuild -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native -verbose 0
/home/vbrankov/.opam/4.02.3/bin/ocamldep.opt -modules hdf5test.ml > hdf5test.ml.depends
/home/vbrankov/.opam/4.02.3/bin/ocamlc.opt -c -I /home/vbrankov/.opam/4.02.3/lib/hdf5_caml -I /home/vbrankov/.opam/4.02.3/lib/hdf5_raw -I /home/vbrankov/.opam/4.02.3/lib/ocaml -o hdf5test.cmo hdf5test.ml
...
```

**Comment by vbrankov** [comment]
When I run this command I get the same output as you:

``` shell
$ ocamlfind ocamlopt -linkpkg -package hdf5_caml -package hdf5_raw -package bigarray hdf5test.cmx -o hdf5test.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Bigarray referenced from /home/vbrankov/.opam/4.02.3/lib/hdf5_raw/hdf5_raw.cmxa(Hdf5_raw)
```

**Comment by nilsbecker** [comment]
weird. no idea what this means. somehow for me the -package specifications are not translated to -I include directories.

wait! i have an alias defined:

```
alias ocamlbuild='ocamlbuild -use-ocamlfind'
```

**Comment by nilsbecker** [comment]
ok, sorry for that. i remove the alias. now i run the same command: 

```
ocamlbuild -pkg bigarray -pkg hdf5_raw -pkg hdf5_caml hdf5test.native -verbose 0
/Users/nbecker/.opam/4.02.3/bin/ocamldep.opt -modules hdf5test.ml > hdf5test.ml.depends
/Users/nbecker/.opam/4.02.3/bin/ocamlc.opt -c -I /Users/nbecker/.opam/4.02.3/lib/hdf5_caml -I /Users/nbecker/.opam/4.02.3/lib/hdf5_raw -I /Users/nbecker/.opam/4.02.3/lib/ocaml -o hdf5test.cmo hdf5test.ml
/Users/nbecker/.opam/4.02.3/bin/ocamlopt.opt -c -I /Users/nbecker/.opam/4.02.3/lib/hdf5_caml -I /Users/nbecker/.opam/4.02.3/lib/hdf5_raw -I /Users/nbecker/.opam/4.02.3/lib/ocaml -o hdf5test.cmx hdf5test.ml
/Users/nbecker/.opam/4.02.3/bin/ocamlopt.opt -I /Users/nbecker/.opam/4.02.3/lib/hdf5_caml -I /Users/nbecker/.opam/4.02.3/lib/hdf5_raw -I /Users/nbecker/.opam/4.02.3/lib/ocaml /Users/nbecker/.opam/4.02.3/lib/ocaml/unix.cmxa /Users/nbecker/.opam/4.02.3/lib/ocaml/bigarray.cmxa /Users/nbecker/.opam/4.02.3/lib/hdf5_raw/hdf5_raw.cmxa /Users/nbecker/.opam/4.02.3/lib/hdf5_caml/hdf5_caml.cmxa hdf5test.cmx -o hdf5test.native
+ /Users/nbecker/.opam/4.02.3/bin/ocamlopt.opt -I /Users/nbecker/.opam/4.02.3/lib/hdf5_caml -I /Users/nbecker/.opam/4.02.3/lib/hdf5_raw -I /Users/nbecker/.opam/4.02.3/lib/ocaml /Users/nbecker/.opam/4.02.3/lib/ocaml/unix.cmxa /Users/nbecker/.opam/4.02.3/lib/ocaml/bigarray.cmxa /Users/nbecker/.opam/4.02.3/lib/hdf5_raw/hdf5_raw.cmxa /Users/nbecker/.opam/4.02.3/lib/hdf5_caml/hdf5_caml.cmxa hdf5test.cmx -o hdf5test.native
ld: warning: directory not found for option '-L/usr/lib/x86_64-linux-gnu/hdf5/serial'
```

**Comment by vbrankov** [comment]
You need to install the package via OPAM.  It will then install HDF5 dependencies.  To sum it up, you probably need `sudo apt-get install libhdf5-serial-dev`.

**Comment by nilsbecker** [comment]
except for the warning, the program compiles and runs, and file.h5 is created. it contains the array!

**Comment by nilsbecker** [comment]
about libhdf5-serial-dev: not sure if this will work: i'm on os x. so this directory: `'-L/usr/lib/x86_64-linux-gnu/hdf5/serial'` is probably the wrong location anyway? (see above: the library is in `/usr/local/opt/....`)

**Comment by nilsbecker** [comment]
about the `-use-ocamlfind` option: should this not also work in principle? why would it be wrong to use ocamlfind to locate the dependencies? iirc, there was some talk about making that option the default in ocamlfind at some point...

**Comment by nilsbecker** [comment]
fyi, i checked the second example using the ppx extension, and that also builds and runs (except for the same warning), when disabling -use-ocamlfind

**Comment by vbrankov** [comment]
For OS X try `brew install homebrew/science/hdf5`

**Comment by vbrankov** [comment]
It works with `-use-ocamlfind` if you put bigarray at the end:

```
ocamlbuild -use-ocamlfind -pkg hdf5_raw -pkg hdf5_caml -pkg bigarray hdf5test.native
```

**Comment by nilsbecker** [comment]
my hdf5 is installed from homebrew/science. 

my point above was that the path that ocamlbuild tries to link with is a linux-specific location which does not make sense here on os x.

i can confirm that listing bigarray last works with -use-ocamlfind. is it expected that one needs to put bigarray last? to me it seems weird since bigarray should be at the top of the dependency chain?

also with -use-ocamlfind, i still get the warning `directory not found for option '-L/usr/lib/x86_64-linux-gnu/hdf5/serial'`. could it be that some linux-specific paths are hardcoded in the library in some way?

(fwiw, this is all still using the opam pinned version of hdf5-ocaml directly off of github)

**Comment by vbrankov** [comment]
I think that the order of the parameters for ocamlbuild is important.  It is important when invoking the OCaml compiler directly.  I think the same is true for gcc.

I will look into the problems with '-L/usr/lib...'.

**Comment by vbrankov** [comment]
This -L is just a warning.  At this point I'd concentrate on completing the functionality of the main library.
