### ISSUE TITLE
project name hdf5 vs hdf5-ocaml

### ISSUE THREAD

**Issue by kkirstein** [vbrankov/hdf5-ocaml#22]
There seems to be a name clash. When upgrading hdf5-0.1.4 to hdf5-0.1.5 I get an error:
`Error: I don't know about package hdf5 (passed through --only-packages/--release)`

It looks like the opam package name has changed from hdf5 to hdf5-ocaml, as the following works:
`opam pin add hdf5-ocaml <path/to/local/repo>` while `opam pin add hdf5 <path/to/local/repo>`  fails with the same message as above.

Did you intentionally rename it to `hdf5-ocaml`?

**Comment by vbrankov** [comment]
No, this was an error.  I hope it is fixed in OPAM now.  The procedure that uploads the project to OPAM was changed and I think it now assumes that the OPAM name is the same as the GitHub project name.  Here are ther details:

https://github.com/ocaml/opam-repository/pull/14356
https://github.com/ocaml/opam-repository/pull/14417

**Comment by kkirstein** [comment]
Thanks for the feedback! I will give it another try when the respective PR in opam-repository has been merged.

**Comment by kkirstein** [comment]
Sorry for the late feedback (got interrupted by another project). I still can't upgrade as `hdf5`, it installs just an empty folder (only with meta files). Looks like building `hdf5` is not triggered by `opam install hdf5`. But I have a workaround by pinning a local repo and installing as `opam install hdf5-ocaml`.

**Comment by vbrankov** [comment]
I see, this is still not working.  I made a new attempt at fixing it:

https://github.com/ocaml/opam-repository/pull/14536

**Comment by vbrankov** [comment]
Thanks for reporting.

**Comment by vbrankov** [comment]
I just did `opam update` and `opam upgrade` and it seems to have installed hdf5 correctly.

**Comment by kkirstein** [comment]
I will give it another try next week (currently on vacation).

**Comment by kkirstein** [comment]
I can confirm that the issue is fixed. Sorry for the late feedback.
