### ISSUE TITLE
weird segfault

### ISSUE THREAD

**Issue by ghennequin** [vbrankov/hdf5-ocaml#4]
I have a weird segfault

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555e9674 in caml_empty_minor_heap () at minor_gc.c:381
```

which occurs when

- I create a _large_ bigarray, and
- I subsequently open an hdf5 file

In the code below, the segfault disappears if either
- I make the array size `n` smaller by one (found this threshold of `16_776_796` through bisection), OR
- I comment out the last 2 lines (i.e. if I don't open the hdf5 file)

```ocaml
let () =
  let open Bigarray in
  let open Hdf5_raw in
  let n = 16_776_796 in
  let a = Array1.create Float64 c_layout n in
  for i=0 to n-1 do a.{i} <- Random.float 1. done;
  let file = H5f.create "test.h5" [ H5f.Acc.TRUNC ] in
  H5f.close file
 ```

Any idea what might be going on?
Can anyone reproduce this? I have never had any issues with large Bigarrays so far, so I doubt this is a faulty-RAM-type-of-issue.

**Comment by ghennequin** [comment]
update: the following also segfaults

```ocaml
let () = 
  let open Bigarray in
  let open Hdf5_raw in
  let n = 20_000_000 in
  let a = Array1.create Float64 c_layout n in
  for i=0 to n-1 do a.{i} <- Random.float 1. done;
  if false then (
    let file = H5f.create "test.h5" [ H5f.Acc.TRUNC ] in
    H5f.close file;
  )
 ```

(ie `H5f.create` is actually never called) whereas this doesn't:

```ocaml
let () = 
  let open Bigarray in
  let open Hdf5_raw in
  let n = 20_000_000 in
  let a = Array1.create Float64 c_layout n in
  for i=0 to n-1 do a.{i} <- Random.float 1. done
 ```

**Comment by ghennequin** [comment]
any idea, anyone? :smile:

**Comment by struktured** [comment]
@ghennequin care to try my branch out? See if it makes any difference. Also, you might want to rerun the test with `OCAMLRUNPARAM` set with GC debugging.

**Comment by vbrankov** [comment]
I merged @struktured 's fixed and committed a few more.  I tried all three of @ghennequin 's examples and I didn't get any segfaults.  Let me know if you're happy with it and I'll brew a new OPAM release.

**Comment by struktured** [comment]
I also have some alternative versions of the `read_string_array` functions that worked better for me at least, but that can be done on a subsequent release. It needs some cleanup and discussion before a PR, anyhow. Thanks for merging in the fixes!

**Comment by vbrankov** [comment]
I think this issue can be closed.

**Comment by ghennequin** [comment]
Thank you all; yes this new version is working well here.
